### ISSUE TITLE
Email service support SMTP

### ISSUE THREAD

**Issue by Ksisu** [TeamWanari/tutelar#31]
Tutelar supports multiple authentication eg.: ldap, oauth2 or email-password. The email-password modul sends emails via `com.wanari.tutelar.providers.userpass.email.EmailService` (it's an interface). Currently it has two implementation: http (call an external http service to send email) and amqp (send mail's data to an external queue like RabbitMQ).

We like to support sending via SMTP, because it is the easiest way.

hints:
- see the two implementation: `com.wanari.tutelar.providers.userpass.email.EmailServiceHttpImpl`, `com.wanari.tutelar.providers.userpass.email.EmailServiceAmqpImpl`
- for testing use the existing `smtp` service (`docker-compose.dev.yml:51`), but you need publish the `1025` port (bc mailhog use this for smtp)
- do not forget about supporting TLS/SSL

Nice to have: some small retry mechanism when sending failed

**Comment by naresh1406** [comment]
I would like to take this.

**Comment by naresh1406** [comment]
@Ksisu I'm trying to set it up locally but facing issues with respect to configuration are not there like clinetId etc. Is it possible to share application.conf file with values.

**Comment by Ksisu** [comment]
First of all: thank you very match and have fun with this! ;)

You got this error because (currently) in the default config the ouath2 modules (`github`, `facebook`, `google`) are enabled. (It's a small bug will fix it soon.)

You only need to remove these from [application.conf#L3](https://github.com/TeamWanari/tutelar/blob/master/src/main/resources/application.conf#L3). eq:
```
modulesEnabled = "health,basic,email,ldap,totp"
```

**Comment by naresh1406** [comment]
Thanks, Yes I'm able to run it locally.

**Comment by naresh1406** [comment]
Now my application is up, but I'm not sure does I missed any step. Whil trying to send mail using existing http protocol getting below error any idea what is wrong?

{"@timestamp":"2019-10-17T23:45:09.892+07:00","@version":"1","message":"Connection attempt failed. Backing off new connection attempts for at least 100 milliseconds.","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"tutelar-system-akka.actor.default-dispatcher-22","level":"WARN","level_value":30000,"sourceThread":"tutelar-system-akka.actor.default-dispatcher-4","akkaSource":"tutelar-system/Pool(shared->http://localhost:9010)","sourceActorSystem":"tutelar-system","akkaTimestamp":"16:45:09.892UTC"}
{"@timestamp":"2019-10-17T23:45:09.893+07:00","@version":"1","message":"Unhandled error!","logger_name":"API","thread_name":"tutelar-system-akka.actor.default-dispatcher-22","level":"ERROR","level_value":40000,"stack_trace":"akka.stream.StreamTcpException: Tcp command [Connect(localhost:9010,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused\nCaused by: java.net.ConnectException: Connection refused\n\tat sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)\n\tat akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$3(TcpOutgoingConnection.scala:103)\n\tat akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:50)\n\tat akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:103)\n\tat akka.actor.Actor.aroundReceive(Actor.scala:539)\n\tat akka.actor.Actor.aroundReceive$(Actor.scala:537)\n\tat akka.io.TcpConnection.aroundReceive(TcpConnection.scala:32)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:581)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:229)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:241)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n","requestId":"6526ee49-7c42-4489-a13f-740a014cf338"}

**Comment by tg44** [comment]
Do you have all the needed containers up and running? 
(`make up` or `docker-compose -f docker-compose.dev.yml up -d`)
